# Generated by Django 5.0.6 on 2026-06-09 15:28

import django.db.models.deletion
import uploads.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_id', models.CharField(blank=True, db_index=True, help_text='FK to course — string for now, FK later', max_length=100, null=True)),
                ('file', models.FileField(upload_to=uploads.models.upload_path)),
                ('file_type', models.CharField(choices=[('course_file', 'Course File'), ('grade_sheet', 'Grade Sheet'), ('clo_mapping', 'CLO Mapping'), ('cqi_report', 'CQI Report'), ('assessment', 'Assessment'), ('other', 'Other')], default='other', max_length=30)),
                ('original_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField(help_text='bytes')),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_msg', models.TextField(blank=True)),
                ('extracted_text', models.TextField(blank=True, help_text='Raw text extracted by pdfplumber')),
                ('parsed_data', models.JSONField(blank=True, default=dict, help_text='Structured CQI data after parsing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PDF Upload',
                'verbose_name_plural': 'PDF Uploads',
                'ordering': ['-created_at'],
            },
        ),
    ]
