# Generated by Django 5.0.6 on 2026-06-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfupload',
            name='course_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='parsed_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
